In [7]:
#Assignment No.01 (Group-B)
# Perform the following operations using Python on the Facebook metrics datasets
#a. Create data subsets
#b. Merge Data
#c. Sort Data
#d. Transposing Data
#e. Shape and reshape Data

In [2]:
#import the libraries
import pandas as pd
import numpy as np

In [3]:
#Read dataset
df=pd.read_csv('dataset_Facebook.csv',sep=';')

In [4]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [5]:
#a. Create data subsets

#1.	Create a subset of a Python dataframe using the loc() function
#Extract data of specific rows of a dataframe
df.loc[[1,3,5]]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186

In [6]:
#Create a subset of rows using slicing
df.loc[0:2:10]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100

In [7]:
#Create a subset of particular columns using labels
df.loc[0:5,['Type','Category']]

     Type  Category
0   Photo         2
1  Status         2
2   Photo         3
3   Photo         2
4   Photo         2
5  Status         2

In [8]:
#2. Using Python iloc() function to create a subset of a dataframe
df.iloc[0:5,[0,2]]

   Page total likes  Category
0            139441         2
1            139441         2
2            139441         3
3            139441         2
4            139441         2

In [9]:
#3. Indexing operator to create a subset of a dataframe
df[['Page total likes','Type','Category','comment']]

     Page total likes    Type  Category  comment
0              139441   Photo         2        4
1              139441  Status         2        5
2              139441   Photo         3        0
3              139441   Photo         2       58
4              139441   Photo         2       19
..                ...     ...       ...      ...
495             85093   Photo         3        5
496             81370   Photo         2        0
497             81370   Photo         1        4
498             81370   Photo         3        7
499             81370   Photo         2        0

[500 rows x 4 columns]

In [10]:
#b. Merge Data

df1=df[['Page total likes','Type','Category','comment']]
df1

     Page total likes    Type  Category  comment
0              139441   Photo         2        4
1              139441  Status         2        5
2              139441   Photo         3        0
3              139441   Photo         2       58
4              139441   Photo         2       19
..                ...     ...       ...      ...
495             85093   Photo         3        5
496             81370   Photo         2        0
497             81370   Photo         1        4
498             81370   Photo         3        7
499             81370   Photo         2        0

[500 rows x 4 columns]

In [11]:
df2=df[['Post Month','Post Weekday','Post Hour','Paid']]
df2

     Post Month  Post Weekday  Post Hour  Paid
0            12             4          3   0.0
1            12             3         10   0.0
2            12             3          3   0.0
3            12             2         10   1.0
4            12             2          3   0.0
..          ...           ...        ...   ...
495           1             7          2   0.0
496           1             5          8   0.0
497           1             5          2   0.0
498           1             4         11   0.0
499           1             4          4   NaN

[500 rows x 4 columns]

In [12]:
pd.concat([df1,df2])

,Page total likes,Type,Category,comment,Post Month,Post Weekday,Post Hour,Paid
0,139441.0,Photo,2.0,4.0,NaN,NaN,NaN,NaN
1,139441.0,Status,2.0,5.0,NaN,NaN,NaN,NaN
2,139441.0,Photo,3.0,0.0,NaN,NaN,NaN,NaN
3,139441.0,Photo,2.0,58.0,NaN,NaN,NaN,NaN
4,139441.0,Photo,2.0,19.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,1.0,7.0,2.0,0.0
496,NaN,NaN,NaN,NaN,1.0,5.0,8.0,0.0
497,NaN,NaN,NaN,NaN,1.0,5.0,2.0,0.0
498,NaN,NaN,NaN,NaN,1.0,4.0,11.0,0.0
499,NaN,NaN,NaN,NaN,1.0,4.0,4.0,NaN

In [13]:
#c. Sort Data

#Sorting the Data frame in ascending order 

df.sort_values(by=['Category'])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
144,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
402,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
401,107907,Photo,1,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,116435,Photo,3,5,1,13,0.0,4202,7633,562,481,730,6173,3298,428,3,148.0,16.0,167
359,116091,Photo,3,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335
361,116091,Photo,3,5,6,3,0.0,3332,5797,463,406,552,4347,2330,341,0,87.0,18.0,105
143,136013,Photo,3,10,2,10,1.0,16776,39549,714,440,720,11860,6200,590,10,377.0,60.0,447
162,135617,Photo,3,9,6,10,0.0,7512,13633,769,614,951,5503,3260,530,22,290.0,98.0,410

In [14]:
#Sorting the Data frame in descending order 

df.sort_values(by=['Category'], ascending=False)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
108,136736,Photo,3,10,7,9,0.0,2426,4469,320,237,325,3120,1684,248,7,125.0,16.0,148
322,123047,Photo,3,6,2,5,1.0,3662,6476,560,522,677,4930,2660,319,2,67.0,14.0,83
331,119198,Photo,3,5,3,5,0.0,4344,8025,692,626,872,4911,2528,367,1,107.0,26.0,134
330,120050,Photo,3,5,3,12,0.0,21248,34095,1049,918,1438,11280,6664,536,20,199.0,32.0,251
329,120050,Photo,3,5,4,4,1.0,4032,7278,684,607,848,4935,2644,432,7,139.0,34.0,180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0
110,136736,Photo,1,10,6,10,0.0,1673,3655,338,324,1619,2598,1469,268,2,28.0,4.0,34
339,117764,Photo,1,5,4,10,0.0,18056,32576,1062,875,1389,26514,14728,701,25,307.0,58.0,390
105,137020,Photo,1,10,2,4,0.0,70144,111745,3216,2628,4782,43671,20608,1542,42,955.0,139.0,1136
250,129600,Photo,1,7,7,6,1.0,5848,9068,622,570,795,6651,4212,383,4,71.0,10.0,85

In [15]:
#Sorting Pandas Data frame by putting missing values first

df.sort_values(by=['Category'], na_position='first')

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
144,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
402,107907,Photo,1,4,3,4,1.0,39568,47128,741,652,957,22022,16096,519,4,128.0,17.0,149
401,107907,Photo,1,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,116435,Photo,3,5,1,13,0.0,4202,7633,562,481,730,6173,3298,428,3,148.0,16.0,167
359,116091,Photo,3,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335
361,116091,Photo,3,5,6,3,0.0,3332,5797,463,406,552,4347,2330,341,0,87.0,18.0,105
143,136013,Photo,3,10,2,10,1.0,16776,39549,714,440,720,11860,6200,590,10,377.0,60.0,447
162,135617,Photo,3,9,6,10,0.0,7512,13633,769,614,951,5503,3260,530,22,290.0,98.0,410

In [18]:
#Sorting Data frames by multiple columns but different order

df.sort_values(by=['Type', 'Category'],ascending=[False, True])

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114
183,134879,Video,1,9,2,10,0.0,30624,56950,2080,1956,3253,32033,15744,1376,6,345.0,121.0,472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
425,102112,Link,3,3,1,3,0.0,6876,10885,282,245,337,9403,5752,259,2,68.0,15.0,85

In [24]:
#d. Transposing Data
result = df.transpose()
result

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [36]:
#e. Shape and reshape Data
#Shape Data

df.shape

(500, 19)

In [33]:
#reshape

pt=pd.pivot_table(df,index=['Type','Category'],values='like')

In [34]:
pt

                       like
Type   Category
Link   1          75.650000
       2          32.000000
       3          68.000000
Photo  1         126.000000
       2         235.857143
       3         219.753333
Status 1         136.333333
       2         182.552632
       3         151.500000
Video  1         231.428571